sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: k4F8TpVwE/1txT7MlZecXLWBFasDI0ZLPIOahHjl+ul0GvHs/btWwUSbRi3qoxTNiSD/KDJydRJvTwvUScaQ4UO6trFMH//6mp0l/rGIMoinSd1mqSWfbN0Aa90NBRThKN9y0TJeo9mLqe/bMUBmCTUMm6bhREMbXjAbsLRAOLkcRE8Vpxs7W8o72jn9lmu5k/fsF0TmvDBQEnGV5dSvuSc/TRiUV8iR0Tv/gmJHHmnXWz/4I7jXuaFHSP6EKzln9oxPkWWzl1BwtEVGwCoR9CWRHyNBK8Fwcsbc7L6p41WdAGxO54UnSGhLjv0XiR/Yi99Khamer3YKyn6GW+DRolwTuQLveRarvluU93vB5xz0QRF1AnhnKpI13OjqnKrOVRJVb3NZ7LKCYjZ/tFBor1y5Af8IWqq+lDxnP8qqdeQ7+JIfiPmA/Ld4KX2zkQ2M/p9fn34VGOfoZkSThqS+iNkNJUdMp+M7ZdXMt23hkkQDvSP1lAWfXqJprKnJ7av8WySzNMztthwjQvGaeYmS2F4bL5Jk1EzMv51aEz3CMuXlqVGG/OtY+E38BsI5p7txzFckdZvDaeAFCxlIGxAtbRoDcbuAPGeJ8psKhuJhzwlYP3reEif82Xna4PFRSUA82kHHqu5ONH+R+fV6v9zfcyJ4RRt2BuLJy5GtWARKE6M=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Honor--de-Balzac_3625
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy